### ISSUE TITLE
challenge

### ISSUE THREAD

**Issue by Tresor11-lab** [larymak/Python-project-Scripts#122]
Hey am a beginner and new to this project 
Any one willing to help me on how i can be 
```
part of this project 
what can i do to be among contributors
what is all about this project 
its objectives and goals 
problems that are needed to be solved
```

**Comment by larymak** [comment]
Hello there, IT's good to have you here
To help answer your questions:
- To be part of the project you should be willing to contribute and help others understand what your code is all about
- In order for you to be part of the contributors, Kindly read the README file of the main branch it has detailed instructions on how to get started with contributions.
- The main objective is to help beginners in the language find projects to guide them along and also our incoming goal is to be able to create collaborative tutorials on the projects already shared here.
- You can come up with a problem personally and try to solve it or share it in the slack channel and brainstorm with other members on how to go about it.

Our aim is to help beginners learn and help people get started with open source contribution,

**Comment by tristanHdez18** [comment]
You can check more information here:
https://docs.github.com/en/get-started/quickstart/contributing-to-projects
