### ISSUE TITLE
Bug in CSV_files/read_csv.py: Incorrect Number of Arguments

### ISSUE THREAD

**Issue by oliviaxu39** [larymak/Python-project-Scripts#133]
Hi! I wanted to report a bug I found in [CSV_files/read_csv.py](https://github.com/larymak/Python-project-Scripts/blob/035b9322676cc0f9bc941fef0fd568f6ab0836b7/CSV_files/read_csv.py). I was expecting the program to successfully read a CSV file using the different methods provided (`DictReader` and `Pandas`), but the actual result of running the program results in a `TypeError`. It seems that the `read_using_DictReader` function should take in one positional argument: `path`. However, the function is being called later without any arguments [here](https://github.com/larymak/Python-project-Scripts/blob/035b9322676cc0f9bc941fef0fd568f6ab0836b7/CSV_files/read_csv.py#L24), causing the program to give a `TypeError`. This error can be reproduced by running the program.

**Comment by larymak** [comment]
Working on that to check possible solution for error

**Comment by Ahmed-Hassan00** [comment]
I opened a [Pull Request](https://github.com/larymak/Python-project-Scripts/pull/135) solving this issue.

**Comment by larymak** [comment]
Goof job on the fix and update
