### ISSUE TITLE
Update year to be dynamic - Age Calculator/age.py

### ISSUE THREAD

**Issue by vicinity123** [larymak/Python-project-Scripts#139]
Instead of having a hard-coded number for the year, having it dynamic is much better.

```python
Current_time = 2022
```

If it were to be hard-coded, every year the author would have to update the year. Hence, making it dynamic would be better.

**Comment by Puskchan** [comment]
Can I help solve this issue?

**Comment by ivoryssf** [comment]
Hi! Are you still looking for help on this one? If so, could you let me know if I can contribute? Thank you!

**Comment by larymak** [comment]
@ivoryssf yes, you can add your contribution to the project

**Comment by AkritiAgarwal09** [comment]
Hi
Can I take up this issue?

**Comment by larymak** [comment]
Hi @AkritiAgarwal09 , Yes you may take on the issue

**Comment by larymak** [comment]
Done, Dynamic year has been implemented
