### ISSUE TITLE
README project links redirected to local forked repos

### ISSUE THREAD

**Issue by kaustav202** [larymak/Python-project-Scripts#146]
A lot of users have linked their project in README projects list to their local forked repo.
This can lead to a problem if the local repository is deleted.

=>  `| 52    | [Rain Alert](https://github.com/Puskchan/Python-project-Scripts/tree/main/Rain_Alert)`

The contribution guidelines should be updated to mention that Projects are linked to this base repo only.

**Comment by larymak** [comment]
Thanks for this, will make the update

**Comment by kaustav202** [comment]
no issues : )
Take should I take it up myself?

**Comment by larymak** [comment]
yeah sure go for it

**Comment by kaustav202** [comment]
In have updated the guidelines in 8d64f772a11957b4da0c77276f9ac066aa5eb535

**Comment by larymak** [comment]
Thanks for the update :)
