### ISSUE TITLE
Links in the README are not updated

### ISSUE THREAD

**Issue by arye321** [larymak/Python-project-Scripts#151]
for example 

**Ascii Image Converter** url should be 

[https://github.com/larymak/Python-project-Scripts/tree/main/ART SCRIPTS/image-ascii](https://github.com/larymak/Python-project-Scripts/tree/main/ART%20SCRIPTS/image-ascii)

instead of

https://github.com/larymak/Python-project-Scripts/tree/main/image-ascii

**Comment by larymak** [comment]
Yeah, After the changes of the arrangements in folders, every URL isn't yet updated. Maybe you can take the task to rearrange them...

**Comment by larymak** [comment]
Thanks, let me confirm and afterwards I will close the issue
