### ISSUE TITLE
Unable to clone repository using GitHub desktop on Windows 11

### ISSUE THREAD

**Issue by ehcelino** [larymak/Python-project-Scripts#174]
Hello, I'm trying to clone the https://github.com/larymak/Python-project-Scripts repository on Windows 11 using GitHub desktop, but I get this error: `error: invalid path 'dice_game_"barbut"'` . I am new to git, and I've searched the web for help to no avail.
![image](https://user-images.githubusercontent.com/10258247/184565343-b31fea01-d0e7-4653-b865-72f2ea978b4a.png)

Any help is appreciated!

**Comment by larymak** [comment]
I think most of the time when s such a problem is e encountered it is mostly due to network issues. Chek and e ensure that y your network is stable

**Comment by ehcelino** [comment]
> I think most of the time when s such a problem is e encountered it is mostly due to network issues. Chek and e ensure that y your network is stable

I've tried to clone the repository at different times, but the same problem occur. I've tried once more today after checking my connection for errors, but to no avail.

I suppose the error is related to the " character in the directory/file name. Windows doesn't accept folders with those characters.

**Comment by pushkar7570** [comment]
1. Clone the Git repository locally;
2. 'cd' into the local Git repository folder that has just been cloned;
3. Run **_git reset_**
4. Run **_git config core.protectNTFS false_**
5. Run **_git checkout_** (just git checkout, no * at the end of command).

**Comment by ehcelino** [comment]
It did not work. Git complains about the `dice_game_"barbut"` file.
![image](https://user-images.githubusercontent.com/10258247/186690811-6d0b59ee-f25a-4d74-bfcb-052788d1443b.png)

**Comment by pushkar7570** [comment]
Try again by deleting all the files and downloading them again and use **_git config --global core.protectNTFS false_** .

**Comment by ehcelino** [comment]
> Try again by deleting all the files and downloading them again and use **_git config --global core.protectNTFS false_** .

It worked! Thank you!
