### ISSUE TITLE
Web Interface

### ISSUE THREAD

**Issue by larymak** [larymak/Python-project-Scripts#192]
Some volunteer and create a web interface to display all the projects category-wise, and the cards to link to each project in the repository. Create a simple but good-looking interface to list the projects

**Comment by Das786** [comment]
I am willing to do this task

**Comment by a2937** [comment]
May I take a shot at this?

**Comment by a2937** [comment]
My plan is to use either pure html, css, and javascript with all respective data coming from JSON; or to use Jekyll to create a website and use a collection to build out the cards.

**Comment by a2937** [comment]
Due to some pro and con analysis, I have decided to implement it in Jekyll.

**Comment by larymak** [comment]
As we are all in the spirit of contribution, Is it possible to work as a team?

**Comment by larymak** [comment]
Or you can both work independently and we conduct a quick pollto get best voted up

**Comment by a2937** [comment]
I have no idea how to contact the other individual but am in favor of the poll.

**Comment by larymak** [comment]
> I have no idea how to contact the other individual but am in favor of the poll.

You can always make use of this platform or join the Slack channel, because we will have the poll done there

**Comment by yashviiii** [comment]
@a2937 if u havent already completed the task, i would love to help

**Comment by Das786** [comment]
@yashviiii I have almost completed the project but some design part is remaining if you have no issues we can collabrate

**Comment by yashviiii** [comment]
sure let me know what you need me to do

**Comment by yashviiii** [comment]
@Das786 sure let me know what u need me to do

**Comment by Das786** [comment]
> @Das786 sure let me know what u need me to do

then we will further communicate using discord which can be more convenient
connect me with this Nightbot#3723
