### ISSUE TITLE
Flask Calculator is static

### ISSUE THREAD

**Issue by Drishti-jain21** [larymak/Python-project-Scripts#249]
The simple flask calculator function is not working
It is a static website
I would like to work on it

<img width="527" alt="image" src="https://user-images.githubusercontent.com/100796147/203379852-dc1daec3-d7de-4a0f-bd9e-693aedee0361.png">

after clicking on submit button
<img width="422" alt="image" src="https://user-images.githubusercontent.com/100796147/203379885-d36b3a44-fd75-4190-9161-45689e833166.png">

**Comment by RitiKSIBJr** [comment]
It does works.

**Comment by larymak** [comment]
Kindly go ahead
