### ISSUE TITLE
"Working with CSV files" project does not seem to link to a correct page

### ISSUE THREAD

**Issue by c00kie123** [larymak/Python-project-Scripts#257]
I was just looking through the different scripts and found out project called "Working with CSV" does not seem to link to the correct page. When clicked on it, it gives an 404 error. To solve it, either remove this project or link it correctly. I can help to work on it. Let me know what you think!

**Comment by larymak** [comment]
I think there must be some mess while rearranging the folders, you can handle the issue.

**Comment by c00kie123** [comment]
Done! Check the PR

**Comment by larymak** [comment]
Good job for highlighting and fixing that.
