### ISSUE TITLE
[New Script] Automate Text Bombing

### ISSUE THREAD

**Issue by FahimFBA** [larymak/Python-project-Scripts#330]
**Is your feature request related to a problem? Please describe.**
I want to add a new script that automates text bombing to any messaging platform starting with Facebook messenger to WhatsApp, Telegram, Instagram and anything else.

**Describe the solution you'd like**
I have the project ready [here](https://github.com/FahimFBA/Automate-Text-Bombing). I want to add this to the repo.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by larymak** [comment]
Hi @FahimFBA 
Feel free to add the project and we will check it and get it merged soon.
