### ISSUE TITLE
Need new arrangement of how projects display in the main README

### ISSUE THREAD

**Issue by larymak** [larymak/Python-project-Scripts#34]
new styling

**Comment by fasihhussain** [comment]
Hello, I'm new to open source projects, I have intermediate python skills and I'm familiar with markdown so can I help you with this?

**Comment by larymak** [comment]
Sure, Go ahead and give it a try. Can't wait to see outcome.

**Comment by xolanigumbi** [comment]
> Hello, I'm new to open source projects, I have intermediate python skills and I'm familiar with markdown so can I help you with this?

So, are you done?

**Comment by Mannuel25** [comment]
> new styling

Hello @larymak , could you please assign this to me.

**Comment by larymak** [comment]
> > new styling
> 
> Hello @larymak , could you please assign this to me.

Sure @Mannuel25 go for it..

**Comment by Mannuel25** [comment]
> > > new styling
> > 
> > 
> > Hello @larymak , could you please assign this to me.
> 
> Sure @Mannuel25 go for it..

Okay, thanks :)
