### ISSUE TITLE
Random Password generator can be more explaining.

### ISSUE THREAD

**Issue by Tanish-Panwar** [larymak/Python-project-Scripts#86]
The **RAMDOM PASSWOR GENERATOR**  can be more explaining, using more scratched code with a beginner friendly explanation of the code. Instead of using the String's Ascii we can use Unicode's for generating a more strong random password.
// This might take O(n) but this would help generating more strong password.

**Comment by Atique-7** [comment]
@oyerohabib Hey, i wanna work on it with you. can i?

**Comment by oyerohabib** [comment]
@Atique-7 , of course you can. what part of it do you want to do?

**Comment by Atique-7** [comment]
@oyerohabib Hey, i have never contributed on an open source project but i was looking for someone to help me get started, if you could guide me, I'd be really grateful. I have some django experience.

**Comment by oyerohabib** [comment]
@Atique-7, no problem. You could read up this article. It is very comprehensive on how to contribute to a project. https://www.freecodecamp.org/news/how-to-contribute-to-open-source-projects-beginners-guide/

Should in case you face any issues at any point in time, feel free to ask me, I would be very glad to help.
